# See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# and https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: Something is not working in Remorph
title: "[BUG]: "
labels: ["bug", "needs-triage"]
# assignees:
#   - remorph-write
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: category
    attributes:
      label: Category of Bug / Issue
      description: Please select the category that best describes the bug / issue you are reporting.
      options:
        - ParserError
        - ValidationError
        - LateralColumnAliasError
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: |
        A concise description of what you're experiencing.
        **Do not paste links to attachments with logs and/or images, as all issues with attachments will get deleted.**
        Use the `Relevant log output` field to paste redacted log output without personal identifying information (PII).
        You can Ctrl/Cmd+V the screenshot, which would appear as a rendered image if it doesn't contain any PII.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or Exception details
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: query
    attributes:
      label: Sample Query
      description: Please copy and paste anonymized Query. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system do you have Remorph installed on?
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - latest via Databricks CLI
        - v0.1.5
        - v0.1.4
        - other
      default: 0
    validations:
      required: true
